"""
Nav2 Hybrid Map Launch File - Odometry + LiDAR z mapą proceduralną
Używa:
- Odometry z motor_driver_speed
- LiDAR edge detection dla precyzji
- Procedural map (2m x 1.5m table z krawędziami)
- Hybrid localization (±6-8cm precision)
"""

from launch import LaunchDescription
from launch.actions import IncludeLaunchDescription, DeclareLaunchArgument
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node
from ament_index_python.packages import get_package_share_directory
import os


def generate_launch_description():
    # Get package directories
    pkg_share = get_package_share_directory('mks_motor_control')
    nav2_bringup_dir = get_package_share_directory('nav2_bringup')
    
    # Paths to config files
    nav2_params_file = os.path.join(pkg_share, 'config', 'nav2_params_odom_only.yaml')
    controller_config = os.path.join(pkg_share, 'config', 'controller.yaml')
    urdf_path = os.path.join(pkg_share, 'urdf', 'two_wheel_robot.urdf')
    
    # Map file (generated by generate_table_map.py)
    map_yaml_file = os.path.expanduser('~/maps/table_2x1.5m_edges.yaml')
    
    # Launch arguments
    use_sim_time = LaunchConfiguration('use_sim_time')
    autostart = LaunchConfiguration('autostart')
    map_file = LaunchConfiguration('map', default=map_yaml_file)
    
    declare_use_sim_time_cmd = DeclareLaunchArgument(
        'use_sim_time',
        default_value='False',
        description='Use simulation (Gazebo) clock if true')
    
    declare_autostart_cmd = DeclareLaunchArgument(
        'autostart',
        default_value='True',
        description='Automatically startup the nav2 stack')
    
    declare_map_cmd = DeclareLaunchArgument(
        'map',
        default_value=map_yaml_file,
        description='Path to map YAML file')

    # ============================================================
    # 1. Robot State Publisher
    # ============================================================
    robot_state_publisher_node = Node(
        package='robot_state_publisher',
        executable='robot_state_publisher',
        output='screen',
        parameters=[{
            'robot_description': open(urdf_path).read(),
            'use_sim_time': use_sim_time
        }]
    )

    # ============================================================
    # 2. Motor Driver Speed (z odometrią)
    # ============================================================
    motor_driver_node = Node(
        package='mks_motor_control',
        executable='motor_driver_speed',
        output='screen',
        parameters=[controller_config]
    )

    # ============================================================
    # 3. Map Server - Proceduralna mapa stołu z krawędziami
    # ============================================================
    map_server_node = Node(
        package='nav2_map_server',
        executable='map_server',
        name='map_server',
        output='screen',
        parameters=[{
            'use_sim_time': use_sim_time,
            'yaml_filename': map_file
        }]
    )
    
    # Lifecycle manager for map_server
    lifecycle_manager_map = Node(
        package='nav2_lifecycle_manager',
        executable='lifecycle_manager',
        name='lifecycle_manager_map',
        output='screen',
        parameters=[{
            'use_sim_time': use_sim_time,
            'autostart': autostart,
            'node_names': ['map_server']
        }]
    )

    # ============================================================
    # 4. Hybrid Localization - Odometry + LiDAR Edge Detection
    # ============================================================
    hybrid_localization_node = Node(
        package='mks_motor_control',
        executable='hybrid_localization',
        output='screen',
        parameters=[{'use_sim_time': use_sim_time}]
    )

    # ============================================================
    # 5. Nav2 Bringup (Navigation Stack)
    # ============================================================
    nav2_bringup_launch = IncludeLaunchDescription(
        PythonLaunchDescriptionSource(
            os.path.join(nav2_bringup_dir, 'launch', 'navigation_launch.py')
        ),
        launch_arguments={
            'use_sim_time': use_sim_time,
            'autostart': autostart,
            'params_file': nav2_params_file
        }.items()
    )

    # ============================================================
    # Launch Description
    # ============================================================
    return LaunchDescription([
        # Arguments
        declare_use_sim_time_cmd,
        declare_autostart_cmd,
        declare_map_cmd,
        
        # Nodes
        robot_state_publisher_node,
        motor_driver_node,
        map_server_node,
        lifecycle_manager_map,
        hybrid_localization_node,
        nav2_bringup_launch,
    ])
