#!/bin/bash
# Sprawdź parametry SLAM Toolbox podczas działania

echo "=========================================="
echo "1. PARAMETRY SLAM TOOLBOX"
echo "=========================================="
echo "scan_topic:"
ros2 param get /slam_toolbox scan_topic 2>/dev/null || echo "BŁĄD: Nie można odczytać parametru"
echo ""
echo "scan_buffer_size:"
ros2 param get /slam_toolbox scan_buffer_size 2>/dev/null || echo "BŁĄD: Nie można odczytać parametru"
echo ""
echo "transform_timeout:"
ros2 param get /slam_toolbox transform_timeout 2>/dev/null || echo "BŁĄD: Nie można odczytać parametru"
echo ""
echo "tf_buffer_duration:"
ros2 param get /slam_toolbox tf_buffer_duration 2>/dev/null || echo "BŁĄD: Nie można odczytać parametru"
echo ""

echo "=========================================="
echo "2. SUBSCRIPTIONS SLAM TOOLBOX"
echo "=========================================="
ros2 node info /slam_toolbox 2>/dev/null | grep -A 10 "Subscribers:" || echo "BŁĄD: Nie można odczytać info o nodzie"
echo ""

echo "=========================================="
echo "3. TOPIC INFO"
echo "=========================================="
echo "--- /scan_throttled ---"
ros2 topic info /scan_throttled 2>/dev/null || echo "BŁĄD: Topic /scan_throttled nie istnieje"
echo ""
echo "--- /scan ---"
ros2 topic info /scan 2>/dev/null | head -5 || echo "BŁĄD: Topic /scan nie istnieje"
echo ""

echo "=========================================="
echo "4. TOPIC HZ (5 sekund)"
echo "=========================================="
echo "--- /scan_throttled ---"
timeout 5 ros2 topic hz /scan_throttled 2>/dev/null || echo "BŁĄD: Nie można odczytać częstotliwości"
echo ""

echo "=========================================="
echo "5. TF TREE (sprawdź czy transformacje istnieją)"
echo "=========================================="
echo "--- map -> base_link ---"
timeout 2 ros2 run tf2_ros tf2_echo map base_link 2>&1 | head -3 || echo "BRAK transformacji map->base_link"
echo ""
echo "--- odom -> base_link ---"
timeout 2 ros2 run tf2_ros tf2_echo odom base_link 2>&1 | head -3 || echo "BRAK transformacji odom->base_link"
echo ""
echo "--- base_link -> unilidar_lidar ---"
timeout 2 ros2 run tf2_ros tf2_echo base_link unilidar_lidar 2>&1 | head -3 || echo "BRAK transformacji base_link->unilidar_lidar"
echo ""
